[template]
keys = ["/"]

owner = "haproxy-app"
mode = "0644"
src = "haproxy.tmpl"
dest = "/usr/local/etc/haproxy/haproxy.cfg"

check_cmd = "/usr/local/sbin/haproxy -c -f {{ .src }}"
reload_cmd = """kill -s SIGUSR2 $(cat $HAPROXY_PID)"""
