[template]
keys = [
  "/proxy/front-ends",
  "/proxy/back-ends"
]

owner = "haproxy-app"
mode = "0644"
src = "haproxy.tmpl"
dest = "/usr/local/etc/haproxy/haproxy.cfg.erb"

check_cmd = "/scripts/check-config.sh {{ .src }}"
reload_cmd = "/scripts/reload-via-multibinder.sh"
