[template]
prefix = "haproxy-discover"
keys = [
  "services",
  "tcp-services"
]

owner = "root"
mode = "0644"
src = "haproxy.tmpl"
dest = "/usr/local/etc/haproxy/haproxy.cfg.erb"

check_cmd = "cp {{ .src }} /tmp/check_config.erb && MULTIBINDER_SOCK= /usr/bin/multibinder-haproxy-erb haproxy -c -f /tmp/check_config.erb"
reload_cmd = "/usr/bin/multibinder-haproxy-wrapper haproxy -f /usr/local/etc/haproxy/haproxy.cfg.erb -p /var/run/haproxy.pid -V"
