[template]
keys = [
  "/proxy/front-ends",
  "/proxy/back-ends"
]

owner = "haproxy-app"
mode = "0644"
src = "haproxy.tmpl"
dest = "/usr/local/etc/haproxy/haproxy.cfg.erb"

check_cmd = "cp {{ .src }} /tmp/check_config.erb && /check_haproxy.sh"
reload_cmd = "/run-or-reload.sh"
